### ISSUE TITLE
Configurable setting for policyLocation

### ISSUE THREAD

**Issue by jmcarless** [jtescher/sbt-jolokia#8]
Hello,

I'd like the ability to set the configuration value for `policyLocation` on the jolokia agent. This would allow me to prevent all requests except from localhost (our telegraf agent).

agent param details: https://jolokia.org/reference/html/agents.html#agents-jvm
info about policy file: https://jolokia.org/reference/html/security.html

Not sure your PR protocol, but seems like it wouldn't be a difficult change to make.

**Comment by jmcarless** [comment]
@jtescher I have a local branch working with this change, do you need to give me access to push the branch up to remote?

**Comment by jtescher** [comment]
You should be able to fork, and push commits to your branch. Then from your branch you should be able to open a PR.

**Comment by jtescher** [comment]
Closed via #9
